regions:
  world:
    1: [20, -64, 20]
    2: [-20, 312, -20]
  world_nether:
    1: [ 20, 0, 20 ]
    2: [ -20, 256, -20 ]
  world_the_end:
    1: [ 20, 0, 20 ]
    2: [ -20, 256, -20 ]

commands-messages:
  mytps: "TPS: %f"
  score-set: "Score %p are set to %a points"
  score-add: "Added %a points from %p score"
  score-remove: "Removed %a points from %p score"