regions:
  world:
    1: [20, -64, 20]
    2: [-20, 312, -20]
  world_nether:
    1: [ 20, 0, 20 ]
    2: [ -20, 256, -20 ]
  world_the_end:
    1: [ 20, 0, 20 ]
    2: [ -20, 256, -20 ]

commands-messages:
  mytps: "TPS: %f"
  score-set: "Score %p are set to %a points"
  score-add: "Added %a points from %p score"
  score-remove: "Removed %a points from %p score"
  score-cd: "Please use this command later!"
  particles-show: "Particles showed"
  particles-hide: "Particles hidden"
  regionwhitelist-add: "Player %p added to server region whitelist"
  regionwhitelist-remove: "Player %p removed from server region whitelist"
  patrol-add: "Added new patrol with name %n"
  patrol-add-err: "A patrol with %n name already exists!"
  patrol-remove: "Removed patrol with name %n"
  patrol-no-exist: "A patrol with %n name no exists!"
  patrol-point-add: "Added new point to patrol %n"
  patrol-owner-err: "You are not owner of this patrol!"
  image-many-requests: "Too many requests! Please try again later"
  image-load-fail: "Failed to load image from link"
  image-load: "Image loaded to map with index %i"
  region-no-selection: "Please create selection with /#wand"