main: study.prikolz.Plugin
version: 1.0
name: PrikolzStudy
api-version: 1.20
permissions:
  command.mytps:
    default: true
  command.reloadconf:
    default: op
  command.invsee:
    default: op
  command.score:
    default: op
  command.regionwhitelist:
    default: op
  command.info:
    default: op
  command.set:
    default: op
  command.sphere:
    default: op